[start]
cmd = "supervisord -c /etc/supervisor/conf.d/supervisord.conf"

[phases.setup]
nixPkgs = ["php", "composer", "nginx", "supervisor", "gnupg"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]